### ISSUE TITLE
Mention CSP in README

### ISSUE THREAD

**Issue by olfek** [hCaptcha/hcaptcha-loader#27]
https://github.com/hCaptcha/hcaptcha-loader/blob/0021ebc024516266cda7b2d5fd1675cf4bffb22d/lib/src/script.ts#L51

https://developer.mozilla.org/docs/Web/HTTP/CSP

**Comment by olfek** [comment]
Probably affects the other similar repositories too.

**Comment by e271828-** [comment]
@olfek presumably you ended up using `strict-dynamic` ?

**Comment by olfek** [comment]
@e271828- ...

Nope, I saved the remote script locally.

I'm working with a browser extension environment.

https://developer.chrome.com/docs/extensions/develop/migrate/improve-security#remove-unsupported-csv

**Comment by e271828-** [comment]
https://github.com/hCaptcha/hcaptcha-loader/pull/30
